apiVersion: v1
kind: Service
metadata:
  name: tc-production-microservice
spec:
  selector:
    app: tc-production-microservice
  ports:
    - protocol: TCP
      port: 80  # Porta exposta do serviço
      targetPort: 80  # Porta no contêiner
  type: LoadBalancer  # Ou ClusterIP, dependendo do seu caso